[workspace]
resolver = "2"
members = ["gateway", "services/user", "shared", "proto"]

[workspace.dependencies]
# Async runtime
tokio = { version = "1", features = ["full"] }

# Web & gRPC
axum = "0.6"
tonic = "0.11"
tonic-build = "0.11"
tonic-reflection = "0.11"
prost = "0.12"

# Database & UUID
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
] }
uuid = { version = "1", features = ["v4", "serde"] }

# Serialization
serde = "1"

# Logging & error handling
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2"

# Env variables
dotenvy = "0.15"
