# ROOT toml


[workspace]
resolver = "3"
members = ["services/product", "services/user", "shared/core"]

[workspace.dependencies]
# Async runtime
tokio = { version = "1.46", features = ["full"] }

# HTTP REST & gRPC
axum = "0.8"
tonic = "0.13"
tonic-build = "0.13"
prost = "0.14"

# Database & serialization
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "uuid"] }
serde = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
dotenvy = "0.15"

# Logging & tracing
tracing = "0.1"
tracing-subscriber = "0.3"

# Error handling
thiserror = "2.0"
