[workspace]
resolver = "2"
members = ["gateway", "services/user", "shared", "proto"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6"
tonic = "0.11"
tonic-build = "0.11"
prost = "0.12"
tonic-reflection = "0.11"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "uuid"] }
uuid = { version = "1", features = ["v4", "serde"] }
serde = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2"
dotenvy = "0.15"
