[package]
name = "proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
