
[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
proto = { path = "../proto" }

tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
